export default ar={
    "welcome-text":"مرحبا بك فى كتاتيب ,بوابة التواصل بين المتعلمين و المحفظين للقرآن الكريم",
    "choose-type":"اختر نوع الحساب",
    "student":"طالب",
    "teacher":"معلم",
    "login":"تسجيل الدخول",
    "welcome-again":"مرحبا بك مجددا",
    "login-by":"تسجيل الدخول باستخدام",
    "email":"البريد الالكترونى",
    "phone":"رقم الهاتف",
    "password":"كلمة المرور",
    "forget-password":"نسيت كلمة المرور؟" ,
    "or-login-by":"أو سجل الدخول باستخدام",
    "donot-have-account":"ليس لديك حساب !",
    "create-account":"أنشئ حساب جديد",
    "required-email":" البريد الالكترونى مطلوب ",
    "invalid-email":"أعد إدخال البريد بشكل صحيح",
    "required-phone":"الهاتف مطلوب",
    "required-password":"كلمة المرور مطلوبة",
    "home":"الرئيسية",
    "my-sessions":"جلساتى",
    "setting":"الاعدادات",
    "my-readings":"قراءاتى",
    "requests":"الطلبات",
    "learning-sessions":"جلسات التعلم ",
    "online-sessions":"جلسات مباشرة",
    "scheduled-sessions":"جلسات مجدولة"

}